[project]
name = "inkview-rs"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
# DATABASE_URL = { description = "Database connection string", required = true }

[profiles.development]
GITHUB_TOKEN = { description = "Github token for git cliff" }
# Development profile inherits all secrets from default profile
# Only define secrets here that need different values or settings than default
# DATABASE_URL = { default = "sqlite:///dev.db" }
#
# New secrets
# REDIS_URL = { description = "Redis connection URL for caching", required = false, default = "redis://localhost:6379" }
